import {ExportLink} from './ExportLink';
import {useEffect,useState,type FormEvent} from 'react';
import {api,ApiError,setCsrf,type User,type ImageRow,type Policy,type Group,type Cluster,type Advice} from './api';

const policyLabels:Record<keyof Policy,string>={blur_min:'Minimum sharpness',luma_min:'Minimum luminance',luma_max:'Maximum luminance',clip_max:'Maximum clipped fraction',contrast_min:'Minimum contrast',review_margin:'Review margin'};
export function App(){
 const [user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true),[mode,setMode]=useState('oidc');
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('Review');
 const [rows,setRows]=useState<ImageRow[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0);
 const [batch,setBatch]=useState(''),[filter,setFilter]=useState(''),[decision,setDecision]=useState('');
 const [policy,setPolicy]=useState<Policy|null>(null),[groups,setGroups]=useState<Group[]>([]),[clusters,setClusters]=useState<Cluster[]>([]);
 const [advice,setAdvice]=useState<Advice|null>(null),[analysis,setAnalysis]=useState<unknown>(null),[audit,setAudit]=useState<unknown[]>([]);
 const admin=user?.roles.includes('admin'),reviewer=admin||user?.roles.includes('reviewer');
 function acceptUser(value:User){setCsrf(value.csrf_token);setUser(value)}
 async function task(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Unexpected error');if(e instanceof ApiError&&e.status===401){setUser(null);setCsrf('')}}finally{setBusy(false)}}
 async function loadRows(page=offset,selected=filter,status=decision){const q=new URLSearchParams({limit:'25',offset:String(page)});if(selected)q.set('batch',selected);if(status)q.set('decision',status);const data=await api<{items:ImageRow[];total:number}>('/images?'+q);setRows(data.items);setTotal(data.total);setOffset(page)}
 const batchQuery=filter?'?batch='+encodeURIComponent(filter):'';
 useEffect(()=>{(async()=>{try{setMode((await api<{mode:string}>('/auth/mode')).mode);try{acceptUser(await api<User>('/auth/me'))}catch(e){if(!(e instanceof ApiError&&e.status===401))throw e}}catch(e){setError(String(e))}finally{setLoading(false)}})()},[]);
 useEffect(()=>{if(user)void task(async()=>{await loadRows(0);setPolicy(await api<Policy>('/policy'))})},[user]);
 async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const input=form.elements.namedItem('images') as HTMLInputElement;const files=Array.from(input.files??[]);if(!files.length)return;await task(async()=>{let created=0,duplicates=0;const failures:string[]=[];for(const file of files){const data=new FormData();data.set('file',file);data.set('batch',batch.trim()||'default');try{const result=await api<{created:boolean}>('/images',{method:'POST',body:data});result.created?created++:duplicates++}catch(e){failures.push(`${file.name}: ${e instanceof Error?e.message:String(e)}`)}}await loadRows(0);setNotice(`${created} imported; ${duplicates} already present.`);if(failures.length)setError(failures.join('\n'));input.value=''})}
 async function showTab(next:string){setTab(next);setAnalysis(null);await task(async()=>{if(next==='Analysis'){const [g,c]=await Promise.all([api<{groups:Group[]}>('/analysis/groups'+batchQuery),api<{clusters:Cluster[]}>('/analysis/clusters'+batchQuery)]);setGroups(g.groups);setClusters(c.clusters)}if(next==='Audit')setAudit((await api<{events:unknown[]}>('/audit')).events)})}
 if(loading)return <main><p role="status">Loading session…</p></main>;
 return <><header><div><span className="eyebrow">DATASET OPERATIONS / RYAN VO</span><h1>Image Quality Observatory</h1><p>Find weak images. Understand patterns. Review with evidence.</p></div>{user&&<div className="identity"><span>{user.username} · {user.roles.join(', ')}</span><button disabled={busy} onClick={()=>void task(async()=>{await api('/auth/logout',{method:'POST'});setCsrf('');setUser(null);setRows([])})}>Sign out</button></div>}</header>
 <main>{error&&<div role="alert" className="error">{error}</div>}{notice&&<div role="status" className="notice">{notice}</div>}
 {!user?<section className="login"><h2>Review your image datasets</h2><p>Measure sharpness, exposure and contrast. Group quality failures, label examples and calibrate a review policy.</p>{mode==='demo'?<><p>Local demo session — development only.</p><button disabled={busy} onClick={()=>void task(async()=>acceptUser(await api<User>('/auth/demo',{method:'POST'})))}>Enter local workspace</button></>:<a className="button" href="/api/auth/login">Sign in with your organization</a>}</section>:<>
 <nav aria-label="Workspace">{['Review','Analysis','Policy',...(admin?['Audit']:[])].map(name=><button key={name} aria-current={tab===name?'page':undefined} disabled={busy} onClick={()=>void showTab(name)}>{name}</button>)}</nav>
 <form className="filters" onSubmit={e=>{e.preventDefault();void task(async()=>{await loadRows(0,batch,decision);setFilter(batch);setAdvice(null);setAnalysis(null);setTab('Review')})}}><label>Batch<input value={batch} onChange={e=>setBatch(e.target.value)} maxLength={100} placeholder="All batches"/></label><label>Decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="">All decisions</option>{['accept','review','reject'].map(d=><option key={d}>{d}</option>)}</select></label><button disabled={busy}>Apply filters</button><span className="muted">Analysis scope: {filter||'all batches'}</span></form>
 {tab==='Review'&&<><section><h2>Image review queue <span className="count">{total}</span></h2>{reviewer&&<form className="upload" onSubmit={upload}><label>Import images into {batch.trim()||'default'}<input name="images" type="file" accept="image/*" multiple required/></label><button disabled={busy}>Measure & import</button></form>}<ExportLink batch={filter}/><p className="muted">Images are measured in memory. Only metrics and metadata are retained.</p><div className="table-wrap"><table><thead><tr><th>Image</th><th>Decision</th><th>Quality</th><th>Failed checks</th><th>Human label</th>{admin&&<th>Manage</th>}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.filename}</strong><small>{row.width} × {row.height} · {row.batch}</small></td><td><span className={'badge '+row.decision}>{row.decision}</span></td><td>{row.quality_score.toFixed(1)}</td><td>{row.failures.join(', ')||'None'}</td><td>{reviewer?<select aria-label={'Label '+row.filename} value={row.label??''} disabled={busy} onChange={e=>void task(async()=>{await api(`/images/${row.id}/label`,{method:'PATCH',body:JSON.stringify({label:e.target.value||null})});await loadRows()})}><option value="">Unlabeled</option><option value="good">Good</option><option value="bad">Bad</option></select>:row.label||'Unlabeled'}</td>{admin&&<td><button className="subtle" disabled={busy} onClick={()=>{if(confirm(`Delete metadata for ${row.filename}? The audit record remains.`))void task(async()=>{await api(`/images/${row.id}`,{method:'DELETE'});await loadRows(Math.max(0,rows.length===1?offset-25:offset))})}}>Delete</button></td>}</tr>)}</tbody></table></div>{!rows.length&&<p className="empty">No images match this view. Import images or change the filters.</p>}<div className="pagination"><button disabled={busy||offset===0} onClick={()=>void task(()=>loadRows(offset-25))}>Previous</button><span>{total?offset+1:0}–{Math.min(offset+25,total)} of {total}</span><button disabled={busy||offset+25>=total} onClick={()=>void task(()=>loadRows(offset+25))}>Next</button></div></section></>}
 {tab==='Analysis'&&<><section><h2>Failure signatures</h2><div className="cards">{groups.map(g=><article key={g.signature}><h3>{g.signature}</h3><strong>{g.count} images</strong><p>Mean quality {g.mean_quality.toFixed(1)}</p></article>)}</div>{!groups.length&&<p>No image measurements in this scope.</p>}</section><section><h2>Metric clusters</h2><div className="cards">{clusters.map(c=><article key={c.index}><h3>Cluster {c.index+1} · {c.size} images</h3><p>{c.description}</p><small>Dominant failure: {c.dominant_failure} · {(c.failure_rate*100).toFixed(0)}% failure rate</small></article>)}</div></section>{reviewer&&<section><h2>Evaluate and explain</h2><p>Calibration uses your good/bad labels. Suggestions are never applied automatically.</p><div className="actions"><button disabled={busy} onClick={()=>void task(async()=>setAnalysis(await api('/analysis/calibrate'+batchQuery,{method:'POST'})))}>Suggest policy</button><button disabled={busy} onClick={()=>void task(async()=>setAnalysis(await api('/analysis/benchmark',{method:'POST'})))}>Run synthetic benchmark</button><button disabled={busy} onClick={()=>void task(async()=>setAdvice(await api<Advice>('/analysis/advice'+batchQuery,{method:'POST'})))}>Explain measurements</button></div>{analysis!==null&&<pre>{JSON.stringify(analysis,null,2)}</pre>}{advice&&<article><h3>{advice.source==='model'?'Model advice':'Local summary'}</h3><p className="preserve">{advice.text}</p>{advice.warning&&<p>{advice.warning}</p>}<small>Advisory only. No images, names or user identifiers are sent to a provider.</small></article>}</section>}</>}
 {tab==='Policy'&&policy&&<section><h2>Quality policy</h2><p>Saving re-evaluates every retained image and records an audit event. Human labels stay unchanged.</p><form onSubmit={e=>{e.preventDefault();if(confirm('Re-evaluate all images using these thresholds?'))void task(async()=>{await api('/policy',{method:'PUT',body:JSON.stringify(policy)});await loadRows();setNotice('Policy saved; all images re-evaluated.')})}}><div className="policy-grid">{(Object.keys(policyLabels) as (keyof Policy)[]).map(key=><label key={key}>{policyLabels[key]}<input type="number" step="any" required disabled={!admin||busy} value={policy[key]} onChange={e=>setPolicy({...policy,[key]:e.target.valueAsNumber})}/></label>)}</div>{admin?<button disabled={busy}>Save policy</button>:<p>Only administrators can edit thresholds.</p>}</form></section>}
 {tab==='Audit'&&admin&&<section><h2>Audit trail</h2><p>Latest 100 events, including retained records of deleted images.</p><pre>{JSON.stringify(audit,null,2)}</pre></section>}
 </>}{busy&&<p role="status" className="working">Working…</p>}</main><footer>Built by Ryan Vo · <a href="mailto:ryandtvo@gmail.com">ryandtvo@gmail.com</a> · v1.0.0</footer></>;
}
